Feature/devise authentication
kisiohlova/onlibrary pull request #10
Opened 2023-11-08 17:27 UTC by kisiohlova

Added Devise Gem
Added Devise tests
Added Devise views
Edited Books views

2023-11-12 13:36 UTC, loqimean requested changes

2023-11-12 13:36 UTC, loqimean commented on app/views/books/_form.html.erb
> +                    label_html: { class: "peer-focus:font-medium absolute text-sm text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:lef
щось це ту матч), давай створюй компоненти)

2023-11-12 13:36 UTC, loqimean commented on app/views/books/_form.html.erb
> +                    label_html: { class: "peer-focus:font-medium absolute text-sm text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:lef
і так скрізь

2023-11-12 13:36 UTC, loqimean commented on bin/dev
чому цей файл пустий?)

2023-11-12 13:40 UTC, kisiohlova commented on app/views/books/_form.html.erb
> +                    label_html: { class: "peer-focus:font-medium absolute text-sm text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:lef
Створила. Просто в наступних комітах) [Тут компоненти](https://github.com/kisiohlova/onlibrary/blob/b03857249144c36a9ff73e85a51770fc291a5c0e/app/assets/stylesheets/components/forms.css). [Тут форма](https://github.com/kisiohlova/onlibrary/blob/b03857249144c36a9ff73e85a51770fc291a5c0e/app/views/books/_form.html.erb).

2023-11-13 09:37 UTC, loqimean approved these changes

2023-11-13 09:39 UTC, merged