Feature/active storage
kisiohlova/onlibrary pull request #14
Opened 2023-11-14 20:52 UTC by kisiohlova

Add Active Storage
Change Views
Add Tests

2023-11-15 18:12 UTC, loqimean requested changes

2023-11-15 18:12 UTC, loqimean commented on app/views/books/show.html.erb
> +        <h3 class="card-isbn">ISBN: <%=@book.isbn%></h3>
```suggestion
        <h3 class="card-author">by <%= @book.author%></h3>
        <h3 class="card-isbn">ISBN: <%= @book.isbn%></h3>
```

2023-11-15 18:12 UTC, loqimean commented on spec/factories/books.rb
> +        book.cover.attach(io: File.open(Rails.root.join("spec", "fixtures", "files", "example_cover.jpg")), filename: "example_cover.jpg", content_type: "image/jpeg")
а якщо це не білд? воно заатачить? ну якщо я відразу викличу `create`

2023-11-15 18:40 UTC, kisiohlova commented on spec/factories/books.rb
> +        book.cover.attach(io: File.open(Rails.root.join("spec", "fixtures", "files", "example_cover.jpg")), filename: "example_cover.jpg", content_type: "image/jpeg")
Наскільки я розумію, то build використовується, коли обʼєкт створюється в памʼяті, а create коли і створюється в памʼяті, і зберігається в бд. Тому тут, мабуть, краще create?

2023-11-15 18:50 UTC, loqimean requested changes

2023-11-15 18:50 UTC, loqimean commented on spec/factories/books.rb
> +        book.cover.attach(io: File.open(Rails.root.join("spec", "fixtures", "files", "example_cover.jpg")), filename: "example_cover.jpg", content_type: "image/jpeg")
ні, питання в тому, що буде, якщо я викличу не білд, а кріейт

2023-11-15 18:50 UTC, loqimean commented on spec/factories/books.rb
> +        book.cover.attach(io: File.open(Rails.root.join("spec", "fixtures", "files", "example_cover.jpg")), filename: "example_cover.jpg", content_type: "image/jpeg")
типу чому ти робиш так, а не передаєш поле файла так само, як і інші поля вище

2023-11-16 14:15 UTC, kisiohlova commented on spec/factories/books.rb
> +        book.cover.attach(io: File.open(Rails.root.join("spec", "fixtures", "files", "example_cover.jpg")), filename: "example_cover.jpg", content_type: "image/jpeg")
Done [here](https://github.com/kisiohlova/onlibrary/pull/14/commits/df21cbcbe44029ef7cc01129022b18566f63d691).

2023-11-16 14:40 UTC, loqimean approved these changes

2023-11-16 14:43 UTC, merged